(()=>{
const P='workReport:',ORDER=P+'sectionOrderV2';
const defs=[['staffMembers','出勤メンバー'],['monthlyGoal','今月目標'],['dailyTodo','本日のやること'],['earlyTodo','早番todo'],['beforeGoal','出勤前目標'],['sales','販買実績'],['bbSurvey','BBアンケート'],['oneWord','ヒトコト所感'],['improve','改善期待行動'],['stumble','まごついたところ'],['impression','所感']];
const ids=defs.map(x=>x[0]), defaults=Object.fromEntries(defs);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const date=()=>$('#targetDate')?.value||'';
const customKey=()=>`${P}day:${date()}:customSections`;
const getOrder=()=>{let a=[];try{a=JSON.parse(localStorage.getItem(ORDER)||'[]')}catch{};return [...a.filter(x=>ids.includes(x)),...ids.filter(x=>!a.includes(x))]};
const saveOrder=a=>localStorage.setItem(ORDER,JSON.stringify(a));
const cfg=()=>{try{return JSON.parse(localStorage.getItem(P+'sectionConfig')||'{}')}catch{return{}}};
const titles=()=>Object.fromEntries(ids.map(id=>[id,(cfg()[id]?.title||defaults[id]).replace(/^◆+/,'')]));
const customs=()=>{try{return JSON.parse(localStorage.getItem(customKey())||'[]')}catch{return[]}};
const saveCustom=a=>localStorage.setItem(customKey(),JSON.stringify(a));
const reload=()=>$('#targetDate')?.dispatchEvent(new Event('change',{bubbles:true}));
function move(id,d){const a=getOrder(),i=a.indexOf(id),j=i+d;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];saveOrder(a);decorate();reorderEdit();reorderView()}
function reorderEdit(){const edit=$('#editMode');if(!edit)return;const anchor=edit.querySelector('.custom')||$('#editCopyBtn');getOrder().forEach(id=>{const n=edit.querySelector(`[data-section="${id}"]`);if(n)edit.insertBefore(n,anchor)});$$('#editMode [data-add],#editMode .plus').forEach((b,i)=>{if(!b.dataset.movedAdd)b.remove()})}
let busy=false;
function reorderView(){if(busy)return;const v=$('#viewText');if(!v||!v.textContent.includes('◆'))return;const text=v.textContent,lines=text.split('\n'),first=lines.findIndex(x=>x.startsWith('◆'));if(first<0)return;const head=lines.slice(0,first),blocks=[];let cur=[];for(let i=first;i<lines.length;i++){if(lines[i].startsWith('◆')){if(cur.length)blocks.push(cur);cur=[lines[i]]}else cur.push(lines[i])}if(cur.length)blocks.push(cur);const t=titles(),byId={},rest=[];blocks.forEach(b=>{const name=b[0].replace(/^◆+/,'').trim();const id=ids.find(x=>t[x]===name);if(id)byId[id]=b;else rest.push(b)});const out=[...head,...getOrder().flatMap(id=>byId[id]||[]),...rest.flat()];busy=true;v.textContent=out.join('\n');busy=false}
function addPrefix(input){if(input.parentElement?.classList.contains('diamondWrap'))return;const w=document.createElement('div');w.className='diamondWrap';input.parentNode.insertBefore(w,input);w.append(input)}
function customSettings(root){root.querySelector('#patchCustom')?.remove();const a=customs();const box=document.createElement('div');box.id='patchCustom';box.innerHTML=`<div class="small" style="margin:16px 0 6px">追加した項目</div>`+(a.length?a.map((x,i)=>`<div class="patchRow"><div class="patchMove"><button data-cu="${i}" ${i===0?'disabled':''}>↑</button><button data-cd="${i}" ${i===a.length-1?'disabled':''}>↓</button></div><div class="diamondWrap"><input data-cn="${i}" value="${String(x.title||'新しい項目').replace(/^◆+/,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;')}"></div><button class="patchDelete" data-cr="${i}">削除</button></div>`).join(''):'<div class="small">追加項目はありません。</div>');root.append(box);box.querySelectorAll('[data-cn]').forEach(e=>e.oninput=()=>{const x=customs();if(!x[+e.dataset.cn])return;x[+e.dataset.cn].title=e.value.replace(/^◆+/,'');saveCustom(x);const ti=$(`#editMode [data-ct="${e.dataset.cn}"]`);if(ti){ti.value=e.value;ti.dispatchEvent(new Event('input',{bubbles:true}))}});const cm=(i,d)=>{const x=customs(),j=i+d;if(j<0||j>=x.length)return;[x[i],x[j]]=[x[j],x[i]];saveCustom(x);reload();setTimeout(()=>{$('#sectionBtn')?.click();decorate()},0)};box.querySelectorAll('[data-cu]').forEach(e=>e.onclick=()=>cm(+e.dataset.cu,-1));box.querySelectorAll('[data-cd]').forEach(e=>e.onclick=()=>cm(+e.dataset.cd,1));box.querySelectorAll('[data-cr]').forEach(e=>e.onclick=()=>{const x=customs(),i=+e.dataset.cr;if(!x[i]||!confirm(`「${x[i].title||'この項目'}」を削除しますか？`))return;x.splice(i,1);saveCustom(x);reload();setTimeout(()=>{$('#sectionBtn')?.click();decorate()},0)})}
function decorate(){const settings=$('#settings');if(!settings)return;const rows=$$('.setting');if(!rows.length)return;rows.forEach(r=>{const inp=r.querySelector('[data-name]');if(!inp)return;inp.value=inp.value.replace(/^◆+/,'');addPrefix(inp);if(!r.querySelector('.patchMove')){const m=document.createElement('div');m.className='patchMove';m.innerHTML=`<button data-up="${inp.dataset.name}">↑</button><button data-down="${inp.dataset.name}">↓</button>`;r.prepend(m);m.querySelector('[data-up]').onclick=()=>move(inp.dataset.name,-1);m.querySelector('[data-down]').onclick=()=>move(inp.dataset.name,1)}});const map=Object.fromEntries(rows.map(r=>[r.querySelector('[data-name]')?.dataset.name,r]));getOrder().forEach(id=>map[id]&&settings.append(map[id]));const o=getOrder();settings.querySelectorAll('[data-up]').forEach(b=>b.disabled=o.indexOf(b.dataset.up)===0);settings.querySelectorAll('[data-down]').forEach(b=>b.disabled=o.indexOf(b.dataset.down)===o.length-1);customSettings(settings);let add=$('#patchAdd');if(!add){const src=$('#editMode [data-add],#editMode .plus');if(src){add=src;add.id='patchAdd';add.dataset.movedAdd='1';add.className='copy';add.textContent='＋ 項目を追加';settings.after(add)}}reorderEdit()}
const style=document.createElement('style');style.textContent=`#editMode .plus,#editMode [data-add]{display:none!important}.diamondWrap{position:relative;min-width:0}.diamondWrap:before{content:'◆';position:absolute;left:10px;top:50%;transform:translateY(-50%);font-weight:800;z-index:1}.diamondWrap input{padding-left:28px!important;width:100%}.setting{grid-template-columns:auto 1fr auto!important}.patchMove{display:flex;gap:4px}.patchMove button{width:32px;height:32px;padding:0;background:#eef2f7;color:#111827}.patchRow{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;padding:7px 0}.patchRow input{width:100%;padding:9px;border:1px solid #d1d5db;border-radius:9px}.patchDelete{padding:8px 10px;background:#fff1f2;color:#b91c1c}`;document.head.append(style);
const mo=new MutationObserver(()=>{if($('#sectionMode')&&!$('#sectionMode').hidden)decorate();reorderEdit();reorderView()});mo.observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{if(e.target?.id==='sectionBtn')setTimeout(decorate,0);if(e.target?.id==='viewBtn'||e.target?.id==='copyBtn'||e.target?.id==='editCopyBtn')setTimeout(reorderView,0)},true);
setTimeout(()=>{reorderEdit();decorate();reorderView()},50);
})();